// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"true","Custom Image":"poweredbyhldt","Fade Out Time":"120","Fade In Time":"120","Wait Time":"180"}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.04 Use regions to block out Events and/or the player from\r\nbeing able to venture into those spots.","parameters":{"Player Restrict":"9","Event Restrict":"10","All Restrict":"11","Player Allow":"12","Event Allow":"13","All Allow":"14"}},
{"name":"SRD_GameOverCore","status":true,"description":"Gives more options for one's Game Over scene. Common Events can be called and a Retry function has been added.","parameters":{"Default Image":"","== Command Window ==":"","Use Command Window":"true","Command Window Phase":"end","Allow Retry Command":"true","Command Window X":"(Graphics.boxWidth - this._commandWindow.width) / 2","Command Window Y":"(Graphics.boxHeight - this._commandWindow.height) / 2","== Command Texts ==":"","Retry Command Text":"Retry Battle","Load Command Text":"Load Game","Title Command Text":"Return to Title","== Command Events ==":"","Start Common Event":"0","Middle Common Event":"0","End Common Event":"0"}}
];
